/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiRunsRunIdStreamRouteImport } from './routes/api.runs.$runId.stream'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRunIdStreamRoute = ApiRunsRunIdStreamRouteImport.update({
  id: '/api/runs/$runId/stream',
  path: '/api/runs/$runId/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/runs/$runId/stream': typeof ApiRunsRunIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/runs/$runId'
    | '/api/auth/$'
    | '/api/runs/$runId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/runs/$runId'
    | '/api/auth/$'
    | '/api/runs/$runId/stream'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/runs/$runId'
    | '/api/auth/$'
    | '/api/runs/$runId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRunsRunIdStreamRoute: typeof ApiRunsRunIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$runId/stream': {
      id: '/api/runs/$runId/stream'
      path: '/api/runs/$runId/stream'
      fullPath: '/api/runs/$runId/stream'
      preLoaderRoute: typeof ApiRunsRunIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRunsRunIdStreamRoute: ApiRunsRunIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
